ifeq ($(BOARD_USES_TONGXINGZHE),true)
LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE:=TXZCore
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE_CLASS:=APPS
LOCAL_SRC_FILES:=$(LOCAL_MODULE).apk
LOCAL_MODULE_SUFFIX:=$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE:=platform
include $(BUILD_PREBUILT)

endif